# Generated by Django 6.0.4 on 2026-07-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Figura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Alien / Figura')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('imagen', models.FileField(upload_to='figuras/', verbose_name='Imagen de la Figura')),
                ('fecha_adquisicion', models.DateField(verbose_name='Fecha de Adquisición')),
                ('serie', models.CharField(choices=[('Ben 10', 'Ben 10'), ('Ben 10 Alien Force', 'Ben 10 Alien Force'), ('Ben 10 Omniverse', 'Ben 10 Omniverse')], default='Ben 10', max_length=50, verbose_name='Serie de origen')),
            ],
            options={
                'verbose_name': 'Figura',
                'verbose_name_plural': 'Figuras',
                'ordering': ['-fecha_adquisicion'],
            },
        ),
    ]
