# Generated by Django 6.0.4 on 2026-07-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figura',
            name='precio',
            field=models.IntegerField(verbose_name='Precio (CLP)'),
        ),
    ]
