# Generated by Django 6.0.4 on 2026-07-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_alter_figura_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figura',
            name='nombre',
            field=models.CharField(choices=[('Bestia', 'Bestia'), ('Cuatrobrazos', 'Cuatrobrazos'), ('Materia Gris', 'Materia Gris'), ('XLR8', 'XLR8'), ('Ultra-T', 'Ultra-T'), ('Diamante', 'Diamante'), ('Insectoide', 'Insectoide'), ('Acuático', 'Acuático'), ('Fantasmático', 'Fantasmático'), ('Cannonbolt', 'Cannonbolt'), ('Fuego', 'Fuego'), ('Goop', 'Goop'), ('Fuego Pantanoso', 'Fuego Pantanoso'), ('Piedra', 'Piedra'), ('Frío', 'Frío'), ('Humungosaurio', 'Humungosaurio'), ('Cerebrón', 'Cerebrón'), ('Jetray', 'Jetray'), ('Mono Araña', 'Mono Araña'), ('Eco Eco', 'Eco Eco'), ('Alien X', 'Alien X')], default='Fuego', max_length=100, verbose_name='Nombre del Alien'),
        ),
    ]
