# Generated by Django 6.0.4 on 2026-07-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_alter_figura_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Ben Tennyson', max_length=100, verbose_name='Nombre de Coleccionista')),
                ('alien_favorito', models.CharField(default='Fuego', max_length=100, verbose_name='Alien Favorito')),
                ('omnitrix_favorito', models.CharField(choices=[('Clásico', 'Omnitrix Clásico'), ('Ultimatrix', 'Ultimatrix'), ('Omniverse', 'Omnitrix Omniverse'), ('Biomnitrix', 'Biomnitrix')], default='Clásico', max_length=50, verbose_name='Omnitrix Favorito')),
                ('avatar', models.CharField(choices=[('classic', 'Ben Clásico'), ('af', 'Ben Alien Force'), ('ov', 'Ben Omniverse'), ('omnitrix', 'Símbolo Omnitrix')], default='classic', max_length=50, verbose_name='Avatar del Fanático')),
            ],
            options={
                'verbose_name': 'Perfil de Fanático',
                'verbose_name_plural': 'Perfiles de Fanáticos',
            },
        ),
    ]
