# Generated by Django 6.0.4 on 2026-07-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='avatar',
            field=models.CharField(choices=[('icon1', 'Icono 1 (Ben Clásico)'), ('icon2', 'Icono 2 (Ben FA)'), ('icon3', 'Icono 3 (Ben Omniverse)'), ('icon4', 'Icono 4 (Gooppng)'), ('icon5', 'Icono 5 (Alien)')], default='icon1', max_length=50, verbose_name='Avatar del Fanático'),
        ),
    ]
