# Generated by Django 6.0.4 on 2026-07-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0005_alter_perfil_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='rango',
            field=models.CharField(choices=[('recluta', 'Recluta Plomero'), ('cadete', 'Cadete de la Academia'), ('elite', 'Plomero de Élite'), ('magister', 'Magister Plomero'), ('omni', 'Portador del Omnitrix'), ('protector', 'Protector de la Tierra'), ('heroe', 'Héroe del Cosmos')], default='recluta', max_length=50, verbose_name='Rango del Coleccionista'),
        ),
    ]
