# Generated by Django 6.0.4 on 2026-07-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0006_perfil_rango'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='fav_figuras',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Figuras Favoritas'),
        ),
    ]
