# Generated by Django 6.0.4 on 2026-07-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0007_perfil_fav_figuras'),
    ]

    operations = [
        migrations.AddField(
            model_name='figura',
            name='estado',
            field=models.CharField(choices=[('excelente', 'Excelente'), ('bueno', 'Bueno'), ('medio', 'Medio'), ('malo', 'Malo')], default='excelente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='figura',
            name='marca',
            field=models.CharField(choices=[('original', 'Original'), ('fake', 'Fake'), ('bandai', 'Bandai')], default='original', max_length=20, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='figura',
            name='tamano',
            field=models.CharField(choices=[('grande', 'Grande'), ('mediano', 'Mediano'), ('pequeno', 'Pequeño')], default='mediano', max_length=20, verbose_name='Tamaño'),
        ),
    ]
