# Generated by Django 6.0.4 on 2026-07-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0008_figura_estado_figura_marca_figura_tamano'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Alien')),
                ('serie_default', models.CharField(choices=[('Ben 10', 'Ben 10'), ('Ben 10 Alien Force', 'Ben 10 Alien Force'), ('Ben 10 Omniverse', 'Ben 10 Omniverse')], default='Ben 10', max_length=50, verbose_name='Serie de origen por defecto')),
            ],
            options={
                'verbose_name': 'Alien',
                'verbose_name_plural': 'Aliens',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='figura',
            name='nombre',
            field=models.CharField(default='Fuego', max_length=100, verbose_name='Nombre del Alien'),
        ),
    ]
