# Generated by Django 6.0.4 on 2026-07-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0010_alter_alien_serie_default_alter_figura_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alien',
            name='serie_default',
            field=models.CharField(choices=[('Ben 10', 'Ben 10'), ('Ben 10 Alien Force', 'Ben 10 Alien Force'), ('Ben 10 Omniverse', 'Ben 10 Omniverse'), ('Personajes', 'Personajes'), ('Villanos', 'Villanos')], default='Ben 10', max_length=50, verbose_name='Serie de origen por defecto'),
        ),
        migrations.AlterField(
            model_name='figura',
            name='serie',
            field=models.CharField(choices=[('Ben 10', 'Ben 10'), ('Ben 10 Alien Force', 'Ben 10 Alien Force'), ('Ben 10 Omniverse', 'Ben 10 Omniverse'), ('Personajes', 'Personajes'), ('Villanos', 'Villanos')], default='Ben 10', max_length=50, verbose_name='Serie de origen'),
        ),
    ]
