# Generated by Django 6.0.4 on 2026-07-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0011_alter_alien_serie_default_alter_figura_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='figura',
            name='subcategoria',
            field=models.CharField(blank=True, choices=[('', 'Ninguna / Estándar'), ('Alienígenas Desbloqueados', 'Alienígenas Desbloqueados'), ('Supremos', 'Supremos'), ('Ultimate Alien', 'Ultimate Alien')], default='', max_length=50, verbose_name='Subcategoría'),
        ),
    ]
