# Generated by Django 6.0.4 on 2026-07-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0012_figura_subcategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='avatar',
            field=models.CharField(choices=[('ben_clasico', 'Ben 10 (Clásico)'), ('ben_af', 'Ben 10 (Alien Force)'), ('ben_ov', 'Ben 10 (Omniverse)'), ('ralph', 'Ralph'), ('alien_x', 'Alien X'), ('fantasmatico', 'Fantasmático'), ('fuego', 'Fuego'), ('goop', 'Goop'), ('ultra_t', 'Ultra T')], default='ben_clasico', max_length=50, verbose_name='Avatar del Fanático'),
        ),
    ]
