# Generated by Django 6.0.4 on 2026-07-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0013_alter_perfil_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='banner',
            field=models.CharField(default='Alien-x.jpg', max_length=100, verbose_name='Banner de Fondo'),
        ),
    ]
