# Generated by Django 6.0.4 on 2026-07-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0014_perfil_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Alien')),
                ('serie', models.CharField(choices=[('Ben 10', 'Ben 10'), ('Ben 10 Alien Force', 'Ben 10 Alien Force'), ('Ben 10 Omniverse', 'Ben 10 Omniverse'), ('Personajes', 'Personajes'), ('Villanos', 'Villanos')], default='Ben 10', max_length=50, verbose_name='Serie de origen')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Agregado')),
            ],
            options={
                'verbose_name': 'Item de Wishlist',
                'verbose_name_plural': 'Items de Wishlist',
                'ordering': ['-fecha_agregado'],
            },
        ),
    ]
