# Generated by Django 6.0.4 on 2026-07-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0015_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='estado',
            field=models.CharField(blank=True, choices=[('excelente', 'Excelente'), ('bueno', 'Bueno'), ('medio', 'Medio'), ('malo', 'Malo')], default='excelente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='fecha_adquisicion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Adquisición'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='figuras/', verbose_name='Imagen de la Figura'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='marca',
            field=models.CharField(blank=True, choices=[('original', 'Original'), ('fake', 'Fake'), ('bandai', 'Bandai')], default='original', max_length=20, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='precio',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Precio (CLP)'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='subcategoria',
            field=models.CharField(blank=True, choices=[('', 'Ninguna / Estándar'), ('Alienígenas Desbloqueados', 'Alienígenas Desbloqueados'), ('Supremos', 'Supremos'), ('Ultimate Alien', 'Ultimate Alien')], default='', max_length=50, verbose_name='Subcategoría'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='tamano',
            field=models.CharField(blank=True, choices=[('grande', 'Grande'), ('mediano', 'Mediano'), ('pequeno', 'Pequeño')], default='mediano', max_length=20, verbose_name='Tamaño'),
        ),
    ]
