# Generated by Django 6.0.4 on 2026-07-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0016_wishlistitem_estado_wishlistitem_fecha_adquisicion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alien',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='aliens_db/', verbose_name='Imagen por defecto'),
        ),
    ]
