# Generated by Django 6.0.4 on 2026-07-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0017_alien_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figura',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='figuras/', verbose_name='Imagen de la Figura'),
        ),
    ]
