# Generated by Django 6.0.4 on 2026-07-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0018_alter_figura_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alien',
            options={'ordering': ['orden_aparicion', 'nombre'], 'verbose_name': 'Alien', 'verbose_name_plural': 'Aliens'},
        ),
        migrations.AddField(
            model_name='alien',
            name='orden_aparicion',
            field=models.IntegerField(default=999, verbose_name='Orden de aparición'),
        ),
    ]
