# Generated by Django 6.0.4 on 2026-07-06 23:56

from django.db import migrations

def populate_alien_orders(apps, schema_editor):
    Alien = apps.get_model('collector', 'Alien')
    orders = {
        # Ben 10 (Clásico)
        'Fuego': 1,
        'Bestia': 2,
        'Diamante': 3,
        'XLR8': 4,
        'Materia Gris': 5,
        'Cuatrobrazos': 6,
        'Insectoide': 7,
        'Fantasmático': 8,
        'Ultra-T': 9,
        'Acuático': 10,
        'Cannonbolt': 11,
        'Wildvine': 12,
        'Blitzwolfer': 13,
        'Snare-Oh': 14,
        'Frankenstrike': 15,
        'Upchuck': 16,
        
        # Ben 10 Alien Force / Ultimate Alien
        'Fuego Pantanoso': 17,
        'Eco Eco': 18,
        'Humungosaurio': 19,
        'Jetray': 20,
        'Frío': 21,
        'Piedra': 22,
        'Cerebrón': 23,
        'Mono Araña': 24,
        'Goop': 25,
        'Alien X': 26,
        'Lodestar': 27,
        'Rath': 28,
        'Upchuck AF': 29,
        'Nanomech': 30,
        'Amenaza Acuática': 31,
        'Armadillo': 32,
        'Tortutornado': 33,
        'NRG': 34,
        'Clockwork': 35,
        'Ampfibio': 36,
        'Fasttrack': 37,
        'Eatle': 38,
        'Humungosaurio Supremo': 39,
        'Fuego Pantanoso Supremo': 40,
        'Cannonbolt Supremo': 41,
        'Frío Supremo': 42,
        'Mono Araña Supremo': 43,
        'Eco Eco Supremo': 44,
        'Bestia Suprema': 45,

        # Ben 10 Omniverse
        'Bloxx': 46,
        'Feedback': 47,
        'Eatle OV': 48,
        'Crashhopper': 49,
        'Gravattack': 50,
        'Bullfrag': 51,
        'Toepick': 52,

        # Personajes
        'Ben Tennyson': 53,
        'Gwen Tennyson': 54,
        'Max Tennyson': 55,
        'Kevin Levin': 56,
        'Tetrax': 57,

        # Villanos
        'Vulkanus': 58,
        'DNAliens': 59,
        'Highbreed': 60,
    }
    for name, order in orders.items():
        Alien.objects.filter(nombre=name).update(orden_aparicion=order)

def reverse_alien_orders(apps, schema_editor):
    Alien = apps.get_model('collector', 'Alien')
    Alien.objects.all().update(orden_aparicion=999)

class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0019_alter_alien_options_alien_orden_aparicion'),
    ]

    operations = [
        migrations.RunPython(populate_alien_orders, reverse_code=reverse_alien_orders),
    ]

