# Generated by Django 6.0.4 on 2026-07-07 03:08

import collector.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0020_populate_alien_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alien',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to=collector.models.aliens_db_upload_path, verbose_name='Imagen por defecto'),
        ),
        migrations.AlterField(
            model_name='figura',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to=collector.models.figuras_upload_path, verbose_name='Imagen de la Figura'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to=collector.models.figuras_upload_path, verbose_name='Imagen de la Figura'),
        ),
    ]
