# Generated by Django 6.0.4 on 2026-07-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0021_alter_alien_imagen_alter_figura_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='figura',
            name='estado_coleccion',
            field=models.CharField(choices=[('coleccion', 'En Colección'), ('bodega', 'En Bodega'), ('vendido', 'Vendido')], default='coleccion', max_length=20, verbose_name='Estado de Colección'),
        ),
    ]
