# Generated by Django 6.0.4 on 2026-07-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0022_figura_estado_coleccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='figura',
            name='precio_venta',
            field=models.IntegerField(blank=True, null=True, verbose_name='Precio de Venta (CLP)'),
        ),
    ]
