# Generated by Django 6.0.4 on 2026-07-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0023_figura_precio_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='avatar',
            field=models.CharField(choices=[('ben_clasico', 'Ben 10 (Clásico)'), ('ben_af', 'Ben 10 (Alien Force)'), ('ben_ov', 'Ben 10 (Omniverse)'), ('ralph', 'Ralph'), ('alien_x', 'Alien X'), ('fantasmatico', 'Fantasmático'), ('fuego', 'Fuego'), ('goop', 'Goop'), ('ultra_t', 'Ultra T'), ('ben_10k', 'Ben 10.000 (Diseño 1)'), ('ben_10k_2', 'Ben 10.000 (Diseño 2)'), ('ben_10k_3', 'Ben 10.000 (Diseño 3)')], default='ben_clasico', max_length=50, verbose_name='Avatar del Fanático'),
        ),
    ]
