# Generated by Django 6.0.4 on 2026-08-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0024_alter_perfil_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='alien',
            name='subcategoria',
            field=models.CharField(blank=True, choices=[('', 'Ninguna / Estándar'), ('Alienígenas Desbloqueados', 'Alienígenas Desbloqueados'), ('Supremos', 'Supremos'), ('Ultimate Alien', 'Ultimate Alien')], default='', max_length=50, verbose_name='Subcategoría'),
        ),
    ]
